# .bash_aliases

# 备份库
export MTMKRES=$HOME/resources
export MTMKFLEX=/home/matt/resources/mygit/stuff/bash/flexec.sh


# 英语帮助
#export MANPATH="/usr/share/man"
#alias eman='man -M /usr/share/man'

# maven
export M2_HOME=$MTMKRES/mybin/maven
export PATH=$M2_HOME/bin:$PATH

# jdk
export JAVA_HOME=$MTMKRES/oraclejava/jdk1.7.0_02
export CLASSPATH=.:$JAVA_HOME/lib
export PATH=$JAVA_HOME/bin:$PATH


# autojump
#source ~/.autojump/etc/profile.d/autojump.zsh
source /etc/profile.d/autojump.bash


# nodejs
export NODE_PATH=/usr/local/lib/node_modules

# 日常维护
# source $MTMKRES/mygit/maintainance/maintainance_completion.sh


# privileged access
if [ $UID -ne 0 ]; then
    alias sudo='sudo '
    alias scat='sudo cat'
    alias svim='sudo vim'
    alias root='sudo su'
    alias pacman='sudo pacman'
    alias reboot='sudo reboot'
    alias halt='sudo halt'
    alias update='sudo pacman -Su'
    alias netcfg='sudo netcfg2'
    alias mount='sudo mount'
    alias umount='sudo umount'
fi

# modified commands
alias diff='colordiff'              # requires colordiff package
alias grep='grep --color=auto'
alias more='less'
alias df='df -h'
alias du='du -c -h'
alias mkdir='mkdir -p -v'
alias ping='ping -c 5'

# new commands
alias da='date "+%A, %B %d, %Y [%T]"'
alias du1='du --max-depth=1'
alias openports='netstat --all --numeric --programs --inet --inet6'
alias pg='ps -Af | grep $1'         # requires an argument (note: /usr/bin/pg is installed by the util-linux package; maybe a different alias name should be used)


# ls
alias ls='ls -hF --color=auto'
alias lr='ls -R'                    # recursive ls
alias ll='ls -l'
alias la='ll -A'
alias lx='ll -BX'                   # sort by extension
alias lz='ll -rS'                   # sort by size
alias lt='ll -rt'                   # sort by date
alias lm='la | more'

# safety features
alias cp='cp -i'
alias mv='mv -i'
alias rm='rm -I'                    # 'rm -i' prompts for every file
alias ln='ln -i'
alias chown='chown --preserve-root'
alias chmod='chmod --preserve-root'
alias chgrp='chgrp --preserve-root'

# 文件和目录
alias del='mv -t ~/.local/share/Trash/files --backup=t'
alias of="xdg-open "
alias ls_d="\ls -1d */"
alias mv2soft=". $MTMKFLEX  'mv %1 ~/resources/softwave/'"
alias mv2doc=". $MTMKFLEX  'mv %1 ~/Documents/'"
alias mv2desk=". $MTMKFLEX  'mv %1 ~/Desktop/'"

# kits
alias ..="cd .."
alias edit_rc="sudo gvim -f /etc/rc.conf &"
alias rexbingkeys='killall -HUP xbindkeys'
alias ccal='cal $(date +%m\ %Y)'
alias lookpath='echo $PATH | tr ":" "\n"'
alias watchprocess='watch "ps -eo pcpu,user,pid,cmd --sort -pcpu | head -6 "'
alias cshort='gnome-desktop-item-edit --create-new ~/Desktop'
alias 9="source ~/.bash_aliases;echo done"
alias xx="quicktar"
alias n="nautilus . "
alias zs="~/bin/look_script_annotation"
alias h=". $MTMKFLEX '%1 --help | less'"
alias ssh2=". $MTMKFLEX  'ssh -p %1 -qTfnN -D 7070 %2 '"
alias nohup2=". $MTMKFLEX 'nohup %1 > /dev/null 2>&1 & '"
alias xyy="nohup2 'wine ~/.wine/drive_c/freegate/FreeU21.exe'"
alias xsel2=". $MTMKFLEX  ' %1 | xsel -b ' "
alias mkdir2=". $MTMKFLEX 'mkdir -pv %1 && cd %1'"
alias mkdir3="mkdir -pv %1 "
alias du2="du -sh "
alias reibus="ibus-daemon -d -x -r"
alias getip="ifconfig | grep -E  'inet\ 地址|inet\ addr' | cut -d ':' -f2 | cut -d ' ' -f1"
alias syncdate="sudo ntpdate -u 192.43.244.18"
alias demsgc="dmesg -T|sed -e 's|\(^.*'`date +%Y`']\)\(.*\)|\x1b[0;34m\1\x1b[0m - \2|g'"
manswitch () { man $1 | less -p "^ +$2"; } 

# grub2
alias arch_grub_install="grub-install --boot-directory=/boot --no-floppy --recheck --debug "
alias arch_grub_update="sudo GRUB_PREFIX="/boot/grub" grub-mkconfig -o /boot/grub/grub.cfg"

# gvim
alias gvimp="gvim -f -p "
alias 8="gvim -f ~/.vimrc &"
alias gs="gvim -S ~/resources/"
alias gf='gvim --remote-silent-tab $1'
alias 0="gvim -f ~/.bash_aliases;echo done &"
alias gs-ubuntu="gvim -S ~/resources/ubuntu.vim &"

# history
alias searchistory="history | grep "
alias history2="history | sed -e 's/\s[0-9\-]\{10\}\s[0-9\:]\{8\}\s//'"
alias r="fc -s "


# pacman aliases (if applicable, replace 'pacman' with your favorite AUR helper)
alias pac="pacman -S"      # default action     - install one or more packages
alias pacu="pacman -Syu"   # '[u]pdate'         - upgrade all packages to their newest version
alias pacs="pacman -Ss"    # '[s]earch'         - search for a package using one or more keywords
alias paci="pacman -Si"    # '[i]nfo'           - show information about a package
alias pacr="pacman -R"     # '[r]emove'         - uninstall one or more packages
alias pacl="pacman -Sl"    # '[l]ist'           - list all packages of a repository
alias pacll="pacman -Qqm"  # '[l]ist [l]ocal'   - list all packages which were locally installed (e.g. AUR packages)
alias paclo="pacman -Qdt"  # '[l]ist [o]rphans' - list all packages which are orphaned
alias paco="pacman -Qo"    # '[o]wner'          - determine which package owns a given file
alias pacf="pacman -Ql"    # '[f]iles'          - list all files installed by a given package
alias pacc="pacman -Sc"    # '[c]lean cache'    - delete all not currently installed package files
alias pacm="makepkg -fci"  # '[m]ake'           - make package from PKGBUILD file in current directory
alias pacw="pacman -Sw"   # 'do[w]nload        - download packages only


# aptitude
#alias i="sudo apt-get install "
#alias i="sudo pacman -S "
#alias s="aptitude search "
#alias upgrade="sudo aptitude upgrade "


# tar
alias tar_delete='tar --delete -f '
alias tar_list='tar tf '
alias tar_update='tar uPvf '
alias tar_extract='tar xPvf '
#alias backup="tar uPvf ~/backup-`lsb_release -r | cut -f 2`.tar /var/cache/apt/archives --exclude=/var/cache/apt/archivesa/partial/* --exclude=/var/cache/apt/archives/lock"

function tar_clear(){
	rm -rf `tar -tf $1`
}


