# Path to your oh-my-zsh configuration.
#ZSH=/usr/share/oh-my-zsh
ZSH=~/.oh-my-zsh

# Set name of the theme to load.
# Look in ~/.oh-my-zsh/themes/
# Optionally, if you set this to "random", it'll load a random theme each
# time that oh-my-zsh is loaded.
#ZSH_THEME="robbyrussell"
#ZSH_THEME="random"
ZSH_THEME="terminalparty"
#ZSH_THEME="my"
#ZSH_THEME="fishy"
# dstufft.zsh-theme

# Example aliases
# alias zshconfig="mate ~/.zshrc"
# alias ohmyzsh="mate ~/.oh-my-zsh"

# Set to this to use case-sensitive completion
# CASE_SENSITIVE="true"

# Comment this out to disable weekly auto-update checks
# DISABLE_AUTO_UPDATE="true"

# Uncomment following line if you want to disable colors in ls
# DISABLE_LS_COLORS="true"

# Uncomment following line if you want to disable autosetting terminal title.
# DISABLE_AUTO_TITLE="true"

# Uncomment following line if you want red dots to be displayed while waiting for completion
# COMPLETION_WAITING_DOTS="true"

# Which plugins would you like to load? (plugins can be found in ~/.oh-my-zsh/plugins/*)
# Custom plugins may be added to ~/.oh-my-zsh/custom/plugins/
# Example format: plugins=(rails git textmate ruby lighthouse)
plugins=(git archlinux autojump)

source $ZSH/oh-my-zsh.sh

# Customize to your needs...


source ~/.zsh_aliases
source ~/bin/aliaswrapper.sh

##在命令前插入 W {{{ #定义功能
W-command-line() {
[[ -z $BUFFER ]] && zle up-history
[[ $BUFFER != W\ * ]] && BUFFER="W $BUFFER"
zle end-of-line                 #光标移动到行末
}
zle -N W-command-line
#定义快捷键为： [Esc] [w]
bindkey "\ew" W-command-line
#}}}

##在命令前插入 sudo {{{ #定义功能
sudo-command-line() {
[[ -z $BUFFER ]] && zle up-history
[[ $BUFFER != sudo\ * ]] && BUFFER="sudo $BUFFER"
zle end-of-line                 #光标移动到行末
}
zle -N sudo-command-line
#定义快捷键为： [Esc] [Esc]
bindkey "\e\e" sudo-command-line
#}}}

# services
#pgrep xbindkeys >/dev/null 2>&1 || xbindkeys
autoload -U url-quote-magic
zle -N self-insert url-quote-magic
#export LANG="en_US.UTF-8"
#export PATH=.:$PATH
#export EDITOR=vim
#export TMPDIR="$HOME/myaourt"
export PATH=$HOME/bin:$PATH
export EDITOR="vim"
export PYTHONPATH="/usr/lib/python2.7/site-packages/"
# 备份库
export MTMKRES=$HOME/resources
#export MTMKFLEX=$MTMKRES/mygit/stuff/bash/flexec.sh

# maven
export M2_HOME=$MTMKRES/mybin/maven
export PATH=$M2_HOME/bin:$PATH

#tmux > /dev/null 2> /dev/null 
# jdk
export JAVA_HOME=$MTMKRES/oraclejava/jdk1.7.0_05
export CLASSPATH=.:$JAVA_HOME/lib
export PATH=$JAVA_HOME/bin:$PATH

#export PATH="/home/matt/Desktop/android-sdk-linux/":$PATH

# nodejs
# export NODE_PATH=/usr/local/lib/node_modules
# echo $PATH

# 调整亮度 
#sudo sh -c "echo 6 > /sys/class/backlight/acpi_video0/brightness"
